/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muts_java;


import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


/**
 *
 * @author derek
 */
public class DataDestForm extends javax.swing.JFrame {

    private Preferences preference;
    /**
     * Creates new form DataDestForm
     */
    public DataDestForm() {
        initComponents();
        folderText.setText(preference.get("XferDataDirectory", ""));
        this.setResizable(false);
    }

    public DataDestForm(Preferences prefs) {
        preference = prefs;
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataDestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataDestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataDestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataDestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        folderText.setText(preference.get("XferDataDirectory", ""));
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        warningText = new javax.swing.JTextArea();
        folderText = new javax.swing.JTextField();
        openDButton = new javax.swing.JButton();
        migrateCB = new javax.swing.JCheckBox();
        applyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        warningText.setEditable(false);
        warningText.setColumns(20);
        warningText.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        warningText.setLineWrap(true);
        warningText.setRows(5);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("muts_java/ES_Bundle_es_GT"); // NOI18N
        warningText.setText(bundle.getString("DataDestWarning")); // NOI18N
        warningText.setWrapStyleWord(true);
        warningText.setAutoscrolls(false);
        warningText.setBorder(null);
        warningText.setFocusable(false);
        warningText.setName(""); // NOI18N
        jScrollPane1.setViewportView(warningText);

        folderText.setEditable(false);

        openDButton.setText("...");
        openDButton.setToolTipText("");
        openDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDButtonActionPerformed(evt);
            }
        });

        migrateCB.setSelected(true);
        migrateCB.setText(bundle.getString("DataDestMigrate")); // NOI18N

        applyButton.setText(bundle.getString("APPLY")); // NOI18N
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(bundle.getString("CANCEL")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(migrateCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(folderText, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(openDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(folderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openDButton))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(migrateCB))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(applyButton)
                            .addComponent(cancelButton))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        this.setAlwaysOnTop(false);
        MUTSLibrary.start_stopService(false,null,false); // stop the service.  
        java.nio.file.Path directPath = java.nio.file.Paths.get(folderText.getText());

        System.out.print(directPath);
        if(Files.isDirectory(directPath, LinkOption.NOFOLLOW_LINKS)){
                    Thread t1 = new Thread(new Runnable() {
            public void run() {
                         
                        preference.put("XferDataDirectory",folderText.getText());
                        MUTSLibrary.start_stopService(true,folderText.getText(),true);
                        } 
            }); t1.start();

            
        }
        else{
            this.setVisible(false);
            JFrame frame = new JFrame();
            frame.requestFocusInWindow();
            frame.requestFocus();
            JOptionPane.showMessageDialog(frame,
                    java.util.ResourceBundle.getBundle("muts_java/ES_Bundle_es_GT").getString("ERROR200"),
                java.util.ResourceBundle.getBundle("muts_java/ES_Bundle_es_GT").getString("DIRECTORYERROR"),
                JOptionPane.ERROR_MESSAGE);
            frame.setAlwaysOnTop(true);
            this.setVisible(true);
        }
        
        int status = MUTSLibrary.getServiceState("MUTSService");
        
        // we have to wait for service to stop or start. This loop waits through
        // the pending stage.
        for(int i = 8; i >0 &&(status == 3 || status == 2); i++){
            try {
                Thread.sleep(1000); // safe, due to countdown. Loop only happens at most 8 times.
            } catch (InterruptedException ex) {
                Logger.getLogger(MUTSLibrary.class.getName()).log(Level.SEVERE, null, ex);
            }
            status = MUTSLibrary.getServiceState("MUTSService");
        }



    }//GEN-LAST:event_applyButtonActionPerformed

    private void openDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDButtonActionPerformed
        JFileChooser chooser = new JFileChooser(); 
        chooser.setDialogTitle(java.util.ResourceBundle.getBundle("muts_java/ES_Bundle_es_GT").getString("CHOOSENEWDATAFOLDER"));
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            folderText.setText(chooser.getSelectedFile().getPath());
        }
        else{
            folderText.setText(preference.get("XferDataDirectory", folderText.getText()));
        }
        
    }//GEN-LAST:event_openDButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public  static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataDestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataDestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataDestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataDestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataDestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField folderText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox migrateCB;
    private javax.swing.JButton openDButton;
    private javax.swing.JTextArea warningText;
    // End of variables declaration//GEN-END:variables
}
